from collections import OrderedDict


DISORDERS = OrderedDict([
    ("acute stress disorder", ["acute stress disorder"]),
    ("add", ["add", "attention deficit disorder"]),
    ("adhd", ["adhd", "attention deficit hyperactivity disorder"]),
    ("adjustment disorder", ["adjustment disorder"]),
    ("antisocial behavior", ["antisocial behavior"]),
    ("agoraphobia", ["agoraphobia"]),
    ("alcohol abuse", ["alcohol abuse", "alcohol use", "alcohol dependence", "alcohol withdrawal", "alcoholic hallucinosis"]),
    ("alzheimer's disease", ["alzheimers", "alzheimer's disease"]),
    ("amnesia", ["amnesia"]),
    ("amnestic disorder", ["amnestic disorder"]),
    ("amphetamine dependence", ["amphetamine dependence"]),
    ("anorexia nervosa", ["anorexia nervosa"]),
    ("anterograde amnesia", ["anterograde amnesia"]),
    ("antisocial behavior", ["antisocial behavior", "antisocial personality disorder"]),
    ("anxiety", ["anxiety", "anxiety disorder"]),
    ("anxiolytic-related disorder", ["anxiolytic-related disorder"]),
    ("asperger syndrome", ["asperger syndrome"]),
    ("atelophobia", ["atelophobia"]),
    ("autism", ["autism"]),
    ("autophagia", ["autophagia"]),
    ("avoidant food intake disorder", ["avoidant food intake disorder"]),
    ("avoidant personality disorder", ["avoidant personality disorder"]),
    ("barbiturate dependence", ["barbiturate dependence"]),
    ("benzodiazepine dependence", ["benzodiazepine dependence", "benzodiazepine misuse", "benzodiazepine withdrawal"]),
    ("bereavement", ["bereavement"]),
    ("bibliomania", ["bibliomania"]),
    ("bipolar", ["bipolar", "bipolar disorder", "bipolar i disorder", "bipolar ii disorder"]),
    ("body dysmorphic disorder", ["body dysmorphic disorder"]),
    ("borderline intellectual functioning", ["borderline intellectual functioning"]),
    ("borderline personality disorder", ["borderline personality disorder"]),
    ("brief psychotic disorder", ["brief psychotic disorder"]),
    ("bulimia nervosa", ["bulimia nervosa", "bulimia", "binge eating disorder", "binge eating", "eating disorder"]),
    ("caffeine-induced anxiety disorder", ["caffeine-induced anxiety disorder"]),
    ("caffeine-induced sleep disorder", ["caffeine-induced sleep disorder"]),
    ("cannabis dependence", ["cannabis dependence"]),
    ("catatonic disorder", ["catatonic disorder"]),
    ("catatonic schizophrenia", ["catatonic schizophrenia"]),
    ("schizophrenia", ["schizophrenia"]),
    ("circadian rhythm sleep disorder", ["circadian rhythm sleep disorder"]),
    ("claustrophobia", ["claustrophobia"]),
    ("cocaine dependence", ["cocaine dependence"]),
    ("cocaine intoxication", ["cocaine intoxication"]),
    ("cognitive disorder", ["cognitive disorder"]),
    ("communication disorder", ["communication disorder"]),
    ("conduct disorder", ["conduct disorder"]),
    ("cotard delusion", ["cotard delusion"]),
    ("cyclothymia", ["cyclothymia"]),
    ("delirium tremens", ["delirium tremens"]),
    ("delusional parasitosis", ["delusional parasitosis"]),
    ("depersonalization disorder", ["depersonalization disorder"]),
    ("depression", ["depression", "depressive disorder"]),
    ("derealization disorder", ["derealization disorder"]),
    ("dermatillomania", ["dermatillomania"]),
    ("desynchronosis", ["desynchronosis"]),
    ("developmental coordination disorder", ["developmental coordination disorder"]),
    ("diogenes syndrome", ["diogenes syndrome"]),
    ("dispareunia", ["dispareunia"]),
    ("dissociative identity disorder", ["dissociative identity disorder"]),
    ("dyslexia", ["dyslexia"]),
    ("dyspraxia", ["dyspraxia"]),
    ("ednos", ["ednos"]),
    ("ekbom's syndrome", ["ekbom's syndrome"]),
    ("encopresis", ["encopresis"]),
    ("enuresis", ["enuresis"]),
    ("epilepsy", ["epilepsy"]),
    ("erotomania", ["erotomania"]),
    ("etoh", ["etoh"]),
    ("exhibitionism", ["exhibitionism"]),
    ("factitious disorder", ["factitious disorder"]),
    ("fregoli delusion", ["fregoli delusion"]),
    ("fugue state", ["fugue state"]),
    ("ganser syndrome", ["ganser syndrome"]),
    ("general adaptation syndrome", ["general adaptation syndrome"]),
    ("generalized anxiety disorder", ["gad", "generalized anxiety disorder"]),
    ("grandiose delusions", ["grandiose delusions"]),
    ("hallucinogen persisting perception disorder", ["hallucinogen persisting perception disorder"]),
    ("hallucinogen-related disorder", ["hallucinogen-related disorder"]),
    ("histrionic personality disorder", ["histrionic personality disorder"]),
    ("huntington's disease", ["huntington's disease"]),
    ("hypnotic-related disorder", ["hypnotic-related disorder"]),
    ("hypochondriasis", ["hypochondriasis"]),
    ("hypomanic episode", ["hypomanic episode"]),
    ("illicit substance use", ["illicit substance", "illicit-substance"]),
    ("poly substance abuse", ["poly substance abuse"]),
    ("insomnia", ["insomnia"]),
    ("intermittent explosive disorder", ["intermittent explosive disorder"]),
    ("kleptomania", ["kleptomania"]),
    ("korsakoff's syndrome", ["korsakoff's syndrome"]),
    ("lacunar amnesia", ["lacunar amnesia"]),
    ("major depressive disorder", ["major depressive disorder"]),
    ("major depressive episode", ["major depressive episode"]),
    ("maladaptive daydreaming", ["maladaptive daydreaming"]),
    ("male erectile disorder", ["male erectile disorder", "erectile dysfunction", "erectile disorder"]),
    ("malingering", ["malingering"]),
    ("manic episode", ["manic episode"]),
    ("mathematics disorder", ["mathematics disorder"]),
    ("melancholia", ["melancholia"]),
    ("minor depressive disorder", ["minor depressive disorder"]),
    ("misophonia", ["misophonia"]),
    ("mixed episode", ["mixed episode"]),
    ("mood disorder", ["mood disorder"]),
    ("munchausen's syndrome", ["munchausen's syndrome"]),
    ("narcissistic personality disorder", ["narcissistic personality disorder"]),
    ("narcolepsy", ["narcolepsy"]),
    ("neurocysticercosis", ["neurocysticercosis"]),
    ("nicotine withdrawal", ["nicotine withdrawal"]),
    ("night eating syndrome", ["night eating syndrome"]),
    ("nightmare disorder", ["nightmare disorder"]),
    ("obsessive compulsive disorder", ["obsessive compulsive", "ocd", "ocpd"]),
    ("odd", ["odd"]),
    ("ondine's curse", ["ondine's curse"]),
    ("oneirophrenia", ["oneirophrenia"]),
    ("opiate dependence", ["opiate dependence"]),
    ("opioid dependence", ["opioid dependence"]),
    ("opioid-related disorder", ["opioid-related disorder"]),
    ("oppositional defiant disorder", ["oppositional defiant disorder"]),
    ("orthorexia", ["orthorexia"]),
    ("pain disorder", ["pain disorder"]),
    ("panic disorder", ["panic disorder"]),
    ("paranoid personality disorder", ["paranoid personality disorder"]),
    ("parasomnia", ["parasomnia"]),
    ("parkinson's disease", ["parkinson's disease"]),
    ("pathological gambling", ["pathological gambling"]),
    ("persecutory delusion", ["persecutory delusion"]),
    ("personality disorder", ["personality disorder"]),
    ("pervasive developmental disorder not otherwise specified (pdd-nos)", ["pervasive developmental disorder not otherwise specified (pdd-nos)"]),
    ("phencyclidine", ["phencyclidine"]),
    ("phobic disorder", ["phobic disorder"]),
    ("phonological disorder", ["phonological disorder"]),
    ("physical abuse", ["physical abuse"]),
    ("pica", ["pica"]),
    ("polysubstance-related disorder", ["polysubstance-related disorder"]),
    ("posttraumatic stress disorder", ["posttraumatic stress disorder", "post traumatic stress", "ptsd", "post-traumatic stress"]),
    ("premature ejaculation", ["premature ejaculation"]),
    ("primary hypersomnia", ["primary hypersomnia"]),
    ("primary insomnia", ["primary insomnia"]),
    ("psychiatric hospitalizations", ["psychiatric hospitalizations"]),
    ("psychogenic amnesia", ["psychogenic amnesia"]),
    ("psychosis", ["psychosis"]),
    ("psychotic disorder", ["psychotic disorder"]),
    ("psychotic", ["psychotic"]),
    ("pyromania", ["pyromania"]),
    ("reactive attachment disorder", ["reactive attachment disorder"]),
    ("recurrent brief depression", ["recurrent brief depression"]),
    ("relational disorder", ["relational disorder"]),
    ("residual schizophrenia", ["residual schizophrenia"]),
    ("restrictive food intake disorder", ["restrictive food intake disorder"]),
    ("retrograde amnesia", ["retrograde amnesia"]),
    ("rumination syndrome", ["rumination syndrome"]),
    ("schizoaffective disorder", ["schizoaffective disorder"]),
    ("schizoid personality disorder", ["schizoid personality disorder"]),
    ("schizophrenia", ["schizophrenia"]),
    ("schizophreniform disorder", ["schizophreniform disorder"]),
    ("schizotypal personality disorder", ["schizotypal personality disorder"]),
    ("seasonal affective disorder", ["seasonal affective disorder"]),
    ("sedative-related disorder", ["sedative-related disorder"]),
    ("selective mutism", ["selective mutism"]),
    ("separation anxiety disorder", ["separation anxiety disorder"]),
    ("severe mental retardation", ["severe mental retardation"]),
    ("shared psychotic disorder", ["shared psychotic disorder"]),
    ("sleep disorder", ["sleep disorder"]),
    ("sleep terror disorder", ["sleep terror disorder", "sleep terror"]),
    ("sleep walking", ["sleep walking", "sleepwalking disorder", "sleepwalking"]),
    ("social anxiety disorder", ["social anxiety disorder"]),
    ("social phobia", ["social phobia"]),
    ("somatization disorder", ["somatization disorder"]),
    ("somatoform disorder", ["somatoform disorder"]),
    ("specific phobia", ["specific phobia"]),
    ("stereotypic movement disorder", ["stereotypic movement disorder"]),
    ("stuttering", ["stuttering"]),
    ("substance-related disorder", ["substance-related disorder"]),
    ("suicidal", ["suicidal behavior", "si", "sa", "suicide"]),
    ("tardive dyskinesia", ["tardive dyskinesia"]),
    ("tourette syndrome", ["tourette syndrome"]),
    ("transient global amnesia", ["transient global amnesia"]),
    ("transient tic disorder", ["transient tic disorder"]),
    ("trichotillomania", ["trichotillomania"]),
])


SYMPTOMS = OrderedDict([
    ('Depression', OrderedDict([
        ('Emotional', ['Sadness', 'anxiety', 'guilt', 'anger', 'mood swings', 'lack of emotion', 'helplessness', 'hopelessness']),
        ('Psychological', ['self-criticism', 'criticizes self', 'self-blame', 'blames self', 'pessimism', 'pessimistic', 'impaired memory', 'bad memory', "impaired concentration", "indecisiveness", "confusion", "thoughts of suicide", "SI", "SA"]),
        ('Behavioral', ['Crying', 'loneliness', 'lonely', 'worrying', 'neglect', 'personal appearance', 'no motivation', 'lacking motivation', 'lacks motivation', 'drug use', 'alcohol use']),
        ('Physical', ['fatigue', 'tired', 'lack of energy', 'overeating', 'loss of appetite', 'constipation', 'weight loss', 'weigth gain', 'irregular menstrual cycle', 'loss of sexual desire', 'aches', 'pains']),
    ])),
    ('Anxiety', OrderedDict([
        ('Physical', ['Heart palpitations', 'chest pain', 'rapid heartbeat', 'flushing', 'hyperventilation', 'hyperventalating', 'shortness of breath', 'dizziness', 'headache', 'sweating', 'tingling', 'numbness', 'choking', 'dry mouth', 'nausea', 'vomiting', 'diarrhea', 'muscle aches', 'restlessness', 'tremors', 'shaking']),
        ('Psychological', ['Unrealistic fear', 'excessive fear', 'excessive worry', 'unrealistic worry', 'mind racing', 'going blank', 'decreased concentration', 'bad memory', 'decreased memory', 'indecisiveness', 'irritability', 'impatience', 'anger', 'confusion', 'restlessness','on edge', 'nervousness', 'nervous', 'tiredness', 'sleep disturbance', 'vivid dreams']),
        ('Behavioral', ['Avoidance', 'avoiding', 'obsessive', 'obsessivness', 'compulsive', 'compulsively', 'distress', 'phobic', 'phobia']),
    ])),
    ('Bi-Polar Disorder', OrderedDict([
        ('Depressive Symptoms', ['Sadness', 'anxiety', 'guilt', 'anger', 'lack of emotion', 'helplessness', 'hopelessness', 'self-criticism', 'criticizes self', 'self-blame', 'blames self', 'pessimism', 'impaired memory', 'impaired concentration', 'indecisiveness', 'confusion', "suicice", "thoughts of suicide", "SI", "SA", 'crying spells', 'crying', 'withdrawal from others', 'worrying', 'worried', 'neglect of responsibilities', 'loss of interest in personal appearance', 'loss of motivation', 'unmotivated', 'chronic fatigue', 'fatigue', 'lack of energy', 'overeating', 'loss of appetite', 'constipation', 'weight loss', 'weight gain', 'loss of sexual desire']),
        ('Manic Symptoms', ['Increased energy', 'overactivity', 'hyperactivity', 'elated mood', 'needing less sleep', 'rapid thinking', 'rapid speech', 'lack of inhibitions', 'grandiose delusions', 'delusions', 'lack of insight']),
    ])),
    ('Psychotic Disorders', OrderedDict([
        ('Changes in Emotion and Motivation', ['Depression', 'anxiety', 'irritability', 'suspiciousness', 'blunted emotion', 'flat emotion', 'inappropriate emotion', 'change in appetite', 'reduced energy', 'reduced motivation']),
        ('Changes in Thinking and Perception', ['Difficulty concentrating', 'difficulty paying attention', 'have changed', 'strange ideas', 'unusual perceptual experiences', 'intensity of sound', 'intensity of color', 'intensity of smell', 'delusions', 'hallucinations']),
        ('Changes in Behavior', ['Sleep disturbance', 'social isolation', 'social withdrawal', 'reduced ability to carry out work']),
    ])),
])


MEDICATIONS = [
    'Abilify', 'Adapin', 'Adderall', 'Alepam', 'Alertec', 'Aloperidin', 'Alplax', 'Alprax', 'Alprazolam', 'Alviz', 'Alzolam', 'Amantadine', 'Ambien', 'Amisulpride', 'Amitriptyline', 'Amoxapine', 'Amfebutamone', 'Anafranil', 'Anatensol', 'Ansial', 'Ansiced', 'Antabus', 'Antabuse', 'Antideprin', 'Anxiron', 'Apo-Alpraz', 'Apo-Primidone', 'Apo-Sertral', 'Aponal', 'Apozepam', 'Aripiprazole', 'Aropax', 'Artane', 'Asendin', 'Asendis', 'Asentra', 'Ativan', 'Atomoxetine', 'Aurorix', 'Aventyl', 'Axoren',
    'Baclofen', 'Beneficat', 'Benperidol', 'Bimaran', 'Bioperidolo', 'Biston', 'Brotopon', 'Bespar', 'Bupropion', 'Buspar', 'Buspimen', 'Buspinol', 'Buspirone', 'Buspisal,Bispa',
    'Cabaser', 'Cabergoline', 'Calepsin', 'Calcium carbonate', 'Calcium carbimide', 'Calmax', 'Carbolith', 'Celexa', 'Chloraldurat', 'Chloralhydrat', 'Chlordiazepoxide', 'Chlorpromazine', 'Cibalith-S', 'Cipralex', 'Citalopram', 'Clomipramine', 'Clonazepam', 'Clozapine', 'Clozaril', 'Concerta', 'Constan', 'Convulex', 'Cylert', 'Cymbalta',
    'Dapotum', 'Daquiran', 'Daytrana', 'Defanyl', 'Dalmane', 'Damixane', 'Demolox', 'Depad', 'Depakene', 'Depakote', 'Depixol', 'Desyrel', 'Dostinex', 'dextroamphetamine', 'Dexedrine', 'Diazepam', 'Didrex', 'Divalproex', 'Dogmatyl', 'Dolophine', 'Droperidol', 'Desoxyn depin',
    'Edronax', 'Effectin', 'Effexor', 'Eglonyl', 'Einalon S', 'Elavil', 'Elontril', 'Endep', 'Epanutin', 'Epitol', 'Evekeo', 'Equetro', 'Escitalopram', 'Eskalith', 'Eskazinyl', 'Eskazine', 'Etrafon', 'Eukystol', 'Eunerpan',
    'Faverin', 'Fazaclo', 'Fevarin', 'Finlepsin', 'Fludecate', 'Flunanthate', 'Fluoxetine', 'Fluphenazine', 'Flurazepam', 'Fluspirilene', 'Fluvoxamine', 'Focalin [Fetzima],',
    'Gabapentin,Geodon', 'Gladem', 'Glianimon,Guanfacine',
    'Halcion', 'Halomonth', 'Haldol', 'Haloperidol', 'Halosten',
    'Imap', 'Imipramine', 'Imovane Itopride',
    'Janimine', 'Jatroneural',
    'Kalma', 'Keselan', 'Klonopin',
    'Lamotrigine', 'Largactil', 'Levomepromazine', 'Levoprome', 'Leponex', 'Lexapro', 'Libotryp Libritabs', 'Librium', 'Linton', 'Liskantin', 'Lithane', 'Lithium', 'Lithizine', 'Lithobid', 'Lithonate', 'Lithotabs', 'Lorazepam', 'Loxapac', 'Loxapine', 'Loxitane', 'Ludiomil', 'Lunesta', 'Lustral', 'Luvox', 'Lyrica', 'Lyogen',
    'Manegan', 'Manerix', 'Maprotiline', 'Mellaril', 'Melleretten', 'Melleril', 'Melneurin', 'Melperone', 'Meresa', 'Mesoridazine', 'Metadate', 'Methamphetamine', 'Methotrimeprazine', 'Methylin', 'Methylphenidate', 'Minitran', 'Mirapex', 'Mirapexine', 'Moclobemide', 'Modafinil', 'Modalina', 'Modecate', 'Moditen', 'Molipaxin', 'Moxadil', 'Murelax', 'Myidone', 'Mylepsinum', 'Mysoline',
    'Nardil', 'Narol', 'Navane', 'Nefazodone', 'Neoperidol', 'Neurontin', 'Nipolept', 'Norebox', 'Normison', 'Norpramine', 'Nortriptyline', 'Novodorm', 'Nitrazepam',
    'Olanzapine', 'Omca', 'Oprymea', 'Orap', 'Oxazepam',
    'Pamelor', 'Parnate', 'Paroxetine', 'Paxil', 'Peluces', 'Pemoline', 'Pergolide', 'Permax', 'Permitil', 'Perphenazine', 'Pertofrane', 'Phenelzine', 'Phenytoin', 'Pimozide', 'Piportil', 'Pipotiazine', 'Pragmarel', 'Pramipexole', 'Pregabalin', 'Primidone', 'Prolift', 'Prolixin', 'Promethazine', 'Prothipendyl', 'Protriptyline', 'Provigil', 'Prozac', 'Prysoline', 'Psymion',
    'Quetiapine',
    'Ralozam', 'Reboxetine', 'Redeptin', 'Resimatil', 'Restoril', 'Restyl', 'Rhotrimine', 'Risperdal', 'Risperidone', 'Rispolept', 'Ritalin', 'Rivotril', 'Rubifen', 'Rozerem',
    'Sediten', 'Seduxen', 'Selecten', 'Serax', 'Serenace', 'Serepax', 'Serenase', 'Serentil', 'Seresta', 'Serlain', 'Serlift', 'Seroquel', 'Seroxat', 'Sertan', 'Sertraline', 'Serzone', 'Sevinol', 'Sideril', 'Sifrol', 'Sigaperidol', 'Sinequan', 'Sinqualone', 'Sinquan', 'Sirtal', 'Solanax', 'Solian', 'Solvex', 'Songar', 'Stazepin', 'Stelazine', 'Stilnox', 'Stimuloton', 'Strattera', 'Sulpiride', 'Sulpiride Ratiopharm', 'Sulpiride Neurazpharm', 'Surmontil', 'Symbyax', 'Symmetrel',
    'Tafil', 'Tavor', 'Taxagon', 'Tegretol', 'Telesmin', 'Temazepam', 'Temesta', 'Temposil', 'Terfluzine', 'Thioridazine', 'Thiothixene', 'Thombran', 'Thorazine', 'Timonil', 'Tofranil', 'Tradon', 'Tramadol', 'Tramal', 'Trancin', 'Tranax', 'Trankimazin', 'Tranquinal', 'Tranylcypromine', 'Trazalon', 'Trazodone', 'Trazonil', 'Trialodine', 'Trevilor', 'Triazolam', 'Trifluoperazine', 'Trihexane', 'Trihexyphenidyl', 'Trilafon', 'Trimipramine', 'Triptil', 'Trittico', 'Troxal', 'Tryptanol,Tryptomer',
    'Ultram',
    'Valium', 'Valproate', 'Valproic acid', 'Valrelease', 'Vasiprax', 'Venlafaxine', 'Vestra', 'Vigicer', 'Vivactil',
    'Wellbutrin',
    'Xanax', 'Xanor', 'Xydep',
    'Zaleplon', 'Zamhexal', 'Zeldox', 'Zimovane', 'Zispin', 'Ziprasidone', 'Zolarem', 'Zoldac', 'Zoloft', 'Zolpidem', 'Zonalon', 'Zopiclone', 'Zotepine', 'Zydis', 'Zyprexa', 'Zuclopenthixol',
]
