PANNS_ITEMS = {
    "positive scale": {
        'P1': 'Delusions',
        'P2': 'Conceptual disorganization',
        'P3': 'Hallucinatory behaviour',
        'P4': 'Excitement',
        'P5': 'Grandiosity',
        'P6': 'Suspiciousness',
        'P7': 'Hostility',
    },
    "negative scale": {
        'N1': 'Blunted affect',
        'N2': 'Emotional withdrawal',
        'N3': 'Poor rapport',
        'N4': 'Passive/apathetic social withdrawal',
        'NS': 'Difficulty in abstract thinking',
        'N6': 'Lack of spontaneity and flow of conversation',
        'N7': 'Stereotyped thinking',
    },
    "general scale": {
        'G1': 'Somatic concern',
        'G2': 'Anxiety',
        'G3': 'Guilt feelings',
        'G4': 'Tension',
        'G5': 'Mannerisms & posturing',
        'G6': 'Depression',
        'G7': 'Motor retardation',
        'G8': 'Uncooperativeness',
        'G9': 'Unusual thought content',
        'G10': 'Disorientation',
        'G11': 'Poor attention',
        'G12': 'Lack of judgment and insight',
        'G13': 'Disturbance of volition',
        'G14': 'Poor impulse control',
        'G15': 'Preoccupation',
        'G16': 'Active social avoidance',
    }
}
